### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException since JRE8 update

### ISSUE THREAD

**Issue by TotalNet** [kayahr/xadrian#13] opened 2015-08-15 04:10 UTC
On a new PC with JRE8 installed the error: java.lang.ArrayIndexOutOfBoundsException comes up in a popup box (Windows x64 build Xadrian 1.5.1) after a few minutes of using the UI.  There doesn't seem to be any specific action that triggers the error but it will trigger after a few minutes of use and interaction with the UI.
using Esc to close the pop up dialogues I can interact with the menu such as saving the game but as soon as the mouse pointer moves over the Xadrian window a new pop up error is displayed.
Another user has reported the same issue since upgrading JRE here: http://forum.egosoft.com/viewtopic.php?p=4543672#4543672
Please feel free to contact me if I can run any logging or other information to help resolve this.

**Comment by kayahr** [comment] 2015-08-21 06:32
Which Java 8 Version are you using? I was able to reproduce the problem with Java 8u45 yesterday and identified the problem as a bug in Java. Today I upgraded to Java 8u60 and now I can no longer reproduce the problem.

**Comment by TotalNet** [comment] 2015-08-21 08:42
Was running 8u45 and have just updated to 8u51 and given it a good bash and seems to be stable now after a reboot. Great news, thanks for responding and thanks too for Xadrian! Cheers.

**Comment by kayahr** [comment] 2016-11-07 14:55
Closing this issue because it looked like a Java update was the solution.

**Closed by kayahr** 2016-11-07 14:55 UTC
Labels: Bug, Confirmed
